# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170603_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Title', max_length=32),
        ),
    ]
